### ISSUE TITLE
Excluding WP-Admin

### ISSUE THREAD

**Issue by spanishgringo** [fastly/WordPress-Plugin#12]
It doesn't look like your plugin sets any varnish rules to exclude wp-admin pages from being cached. I'd suggest you add that as an option in the admin panel.

**Comment by Cjames21082** [comment]
When you install the Wordpress plugin in Fastly there is default code that is added to your generated VCL file. You should see a clause that prevents caching if wp-admin pages:

```
### do not cache these files:
  ## never cache the admin pages, or the server-status page
  if (req.request == "GET" && (req.url ~ "(wp-admin|bb-admin|server-status)")) {
    return(pipe);
  }
```

If you see caching, please open a support ticket so that we can take a look.
