### ISSUE TITLE
Title re-name and re-vamping of instructions 

### ISSUE THREAD

**Issue by Shashimi** [fastly/WordPress-Plugin#13]
We have had other customers in the past mention one or two steps are a bit unclear to them, thus leading to tickets about setting up wordpress; justin from say media had a great suggestion that we should have someone unfamiliar with the wordpress set up the plug-in and then re-vamp our instructions for setting it up with those recommendations in mind. 

Relevant ticket:

https://fastly.zendesk.com/agent/tickets/10721

Also, per customer:

"And one last request, can you please forward along the that the plugin title in the wordpress directory be renamed? Searching for it is nearly impossible in wordpress because it's called "The WordPress Plugin". See here: https://wordpress.org/plugins/fastly/

I'd make it "The fastest caching CDN plugin with instant cache purges plugin, by Fastly!!!!!111". Feel free to use that. ;-)"

**Comment by amandablum** [comment]
I'd make it "Fastly CDN Plugin".That would make it the easiest to find.
