### ISSUE TITLE
Writing a post triggers a broken purge_all request

### ISSUE THREAD

**Issue by jbartus** [fastly/WordPress-Plugin#18]
When saving a post I get this in my error log:

```
Purging using POST for https://api.fastly.com/purge/api.fastly.com/service/ZyhWtT7PgjBK5N4U1KIGk/purge_all, referer: http://jim.bartus.com/blog/wp-admin/post-new.php
```

Note the extraneous "purge/api.fastly.com/" in the middle of the url.

Interesting to note, if you manually curl that url you do get an 'ok' response:

```
{"status": "ok", "id": "324-1446794023-290766"}
```

However in either case (wp issued or hand-curled) it does not actually work, the purge_all never occurs (content stays cached, purge all event never appears in event log).

The person who brought this to my attention points out: 

> It looks like you're overloading your use of post in api.php:
> 
> https://github.com/fastly/WordPress-Plugin/blob/master/lib/api.php
> 
> The post method builds the full URL, which works for purge since it sends a partial URL, but breaks for purgeAll since purgeAll builds the URL itself.

**Comment by kimmi8** [comment]
Yep, there is work going on tangentially around our WP plugin. Will keep you posted.
