### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by Ipstenu** [fastly/WordPress-Plugin#27]
On v 1.1.1 on WP 4.8

> Fatal error: Can't use method return value in write context in /wp-content/plugins/WordPress-Plugin-master/src/classes/vcl-handler.php on line 88

**Comment by vvuksan** [comment]
We'll take a look.

**Comment by Ipstenu** [comment]
I think it's a PHP 5.4 error, looking at the server. You should through in a check for that version of PHP :)

**Comment by vvuksan** [comment]
5.4 is no longer supported.

http://php.net/supported-versions.php

is PHP upgrade a possibility ?

**Comment by Ipstenu** [comment]
We did upgrade to 7 and that fixed it, BUT as the plugin lead for .org, I STRONGLY recommend you error trap the PHP version and give a proper alert to users :) Some will have upgraded without knowing.

**Comment by vvuksan** [comment]
We have a fix in latest version.
