### ISSUE TITLE
Error while purging, check logs

### ISSUE THREAD

**Issue by ain** [fastly/WordPress-Plugin#34]
__Steps to reproduce__:

1. Install and configure Fastly plugin `1.2.1` on Wordpress `4.8.1`
2. Click Test connection in _General settings_ to confirm connection is successful
3. Go to _Advanced_ settings
4. Enter full URL to be purged into  _Purge by URL_ field
5. Click _Purge URL_

__What happens__: `Error while purging, check logs.` error is thrown. `/var/log/nginx/error.log` reveals:

```
2017/09/20 20:56:25 [error] 22984#22984: *3694535 FastCGI sent in stderr: "PHP message: Error occurred, turn on debugging options and check your logs. - Purging URL - <url>" while reading response header from upstream, client: 199.27.76.26, server: _, request: "GET /wp-admin/admin-ajax.php?action=purge_by_url&purge_url=<url> HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "<host>", referrer: "<host>/wp-admin/admin.php?page=fastly-advanced"
```
 
__What should happen__: since connection is successful, one would expect the purge to work.

**Comment by ain** [comment]
Worth mentioning, traffic to Fastly comes from Cloudflare.

**Comment by vvuksan** [comment]
We are looking into it.

**Comment by tnikcevs** [comment]
Hello,

Do you happen to have some information in Cloudflare events when attempting to purge? Have you by chance prevented PURGE method type in Cloudflare (as for Fastly both PURGE and PUT are used besides GET and POST for different types of requests)?

**Comment by vvuksan** [comment]
I am going to close this as we have not had any responses in three weeks and it's likely due to Cloudflare being in front of Fastly and Cloudflare blocking PURGE requests.

**Comment by ain** [comment]
Calling to reopen the ticket as alternative behaviour is needed. Using Cloudflare in front of Fastly is IMO rather common.

As mentioned, Cloudflare blocks `PURGE` requests, for instance:

## Fails

```
curl -X PURGE http://domain.com/subdir/
```

## Succeeds

```
curl -X PURGE -H 'Host: domain.com' a.prod.fastly.net/subdir/
```

Therefore I'd suggest an alternative purging mechanism that works with direct request given the host.

**Comment by vvuksan** [comment]
In most cases our plugin uses purge by key purges which are not affected by this behavior since it communicates directly with our API. Purge by URL is there for convenience and not normally used. You can still purge by URL from the Fastly console. We'll consider it but this is not really a use case we see often.

**Comment by antongorodezkiy** [comment]
Honestly, it was a bit confusing that purge by url function inside Fastly and inside Fastly plugin are doing different things and one may work when other did not. (had the same setup with Faslty+Cloudflare btw)
