### ISSUE TITLE
Error while purging, check logs.

### ISSUE THREAD

**Issue by HayatoIse** [fastly/WordPress-Plugin#57]
# Error
- All purge is possible but single purge is not possible.
- And nothing is written in error log.
- What should I do?
<img width="646" alt="2018-09-18 20 19 30" src="https://user-images.githubusercontent.com/12937048/45684090-35f11480-bb80-11e8-972e-4c61a6fa1e4e.png">

# Environment
- WordPress 4.9.8
- Fastly Plugin 1.2.5
- PHP 7.2.X
- I am using Nginx

**Comment by vvuksan** [comment]
Hi @HayatoIse ,

It doesn't appear that this is an issue with the plugin but with a purge ACL that limits purges to only certain IPs. I suspect your Wordpress server IP is not on that list.

**Comment by HayatoIse** [comment]
@Vanders 
Thank you for your quick reply.
> It doesn't appear that this is an issue with the plugin but with a purge ACL that limits purges to only certain IPs. I suspect your Wordpress server IP is not on that list.
I will check it later.

<img width="158" alt="2018-09-19 14 31 03" src="https://user-images.githubusercontent.com/12937048/45732738-a9defb80-bc18-11e8-857b-3dbc6ea8267c.png">
Actually Purge All works fine.
Is there anything to know about this?

**Comment by HayatoIse** [comment]
@vvuksan 
As you pointed out, it was impossible to purge because an arbitrary IP address was not added to the ACL. Thank you very much for answering.
