### ISSUE TITLE
Fastly Plugin purges only the top page

### ISSUE THREAD

**Issue by HayatoIse** [fastly/WordPress-Plugin#60]
# Overview
- When posting or updating articles in WordPress, Fastly's Plugin will notify Slack of success. However, the cache is purged only on the top page.
![image](https://user-images.githubusercontent.com/12937048/47341214-72fa7a80-d6db-11e8-9c4d-17c401409f58.png)
- Probably the reason is setting the surrogate key.
- In the notification, we have successfully purged p - 25492 t - 94 t - 197 t - 31 t - 35837 t - 32 t - 36 t - 33 t - 34 a - 9 tm - post tm - home tm - feed holos tm - 404 It is informed that it is.
- The surrogate-key in the response header of this page (https://www.ikyu.com/concierge/25492) is described as concierge / concierge / 25492 / concierge.
- Where can I set this surrogate key?
- Or is this solution wrong?

**Comment by vvuksan** [comment]
Hi @HayatoIse ,

you can find out what keys are being set by supplying the Fastly-Debug header e.g.

```curl -HFastly-Debug:1 https://www.ikyu.com/concierge/25492 -v -o /dev/null
```

That specific page sets all of these surrogate keys

< surrogate-key: p-25492 tm-single t-94 t-197 t-31 t-35837 t-32 t-36 t-33 t-34 a-9concierge /concierge/25492 /concierge
