### ISSUE TITLE
upgrade to 1.2.6 caused massive increase in calls to fastly api

### ISSUE THREAD

**Issue by msporleder** [fastly/WordPress-Plugin#63]
We upgraded from 1.2.4 to 1.2.6 and newrelic reported called to fastly api from admin-ajax.php up from (effectively) 0 to 2 calls/s !

This, of course, presented as a big performance hit to us and probably isn't great for the fastly api servers.

I haven't done any bisecting yet but I assume a hook is being hit when it otherwise would not.  (New Relic implies that it is, probably, admin_init)

**Comment by vvuksan** [comment]
Thanks for the report.

**Comment by vvuksan** [comment]
We have fixed this in #64 and #65. Can you install 1.2.7 and verify that it fixes it.
