### ISSUE TITLE
Undefined index: page in plugins/fastly/src/settings-page.php on line 448

### ISSUE THREAD

**Issue by msporleder** [fastly/WordPress-Plugin#67]
The check for $_GET['page'] needs to be inside of something because it is happening for every request (at least to wp-admin/) after upgrading to 1.2.7

    isset($_GET['page'])

maybe?

**Comment by dmbostan** [comment]
I think this was fixed in https://github.com/fastly/WordPress-Plugin/pull/66.

But not yet published on WordPress Plugin Repository.

**Comment by vvuksan** [comment]
It was released as version 1.2.8
